export const ContentActions = {
  CREATE_NEW_ENTRY: 'CREATE_NEW_ENTRY',
  SAVE_ENTRY: 'SAVE_ENTRY',
  LOAD_USER_FROM_SERVER: 'LOAD_USER_FROM_SERVER',
  LOAD_ENTRIES_FROM_SERVER: 'LOAD_ENTRIES_FROM_SERVER',
};
